x-common-setup: &common-setup
  build:
    context: .
    args:
      USER_ID: ${USER_ID:-1000}
      GROUP_ID: ${GROUP_ID:-1000}
  user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
  logging:
    driver: "json-file"
    options:
      max-size: "50m"
      max-file: "3"
  restart: on-failure
  environment:
    - PYTHONPATH=/application
    - PYTHONUNBUFFERED=1
  networks:
    - app-network
  dns:
    - 8.8.8.8
    - 1.1.1.1


services:
  app:

    <<: *common-setup

    volumes:
      - ./application:/application/application
      - ./migrations:/application/migrations
      - ./static:/application/static
      - ./alembic.ini:/application/alembic.ini
      - ./main.py:/application/main.py
      - ./pytest.ini:/application/pytest.ini
      - ./requirement.txt:/application/requirement.txt
      - ./tests:/application/tests
      - ./media:/application/media
      - ./${LOG_PATH:-./logs}:/application/logs
      - ./core:/application/core

    command: ["python", "main.py", "--reload", "--log-level", "debug"]

    ports:
      - "8000:8000"

    env_file:
      - .env
      - .env.test

    depends_on:
      db:
        condition: service_healthy





  fin_bot:

    <<: *common-setup

    volumes:
      - ./financial_bot:/application/financial_bot
      - ./migrations:/application/migrations
      - ./alembic.ini:/application/alembic.ini
      - ./pytest.ini:/application/pytest.ini
      - ./requirement.txt:/application/requirement.txt
      - ./tests:/application/tests
      - ./${LOG_PATH:-./logs}:/application/logs
      - ./core:/application/core

    command: python -m financial_bot.main

    env_file:
      - .env
      - .env.test

    depends_on:
      db:
        condition: service_healthy



  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - db-data:/var/lib/postgresql



    command:
      [
        "postgres",
        "-c", "log_destination=stderr",
        "-c", "logging_collector=on",
        "-c", "log_directory=/var/log/postgresql"
      ]
    networks:
      - app-network

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s


  db_test:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: slava_t
      POSTGRES_PASSWORD: 1989_slava_t
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U slava_t -d test_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - app-network


  redis:
    image: redis:7.4.2-alpine
    restart: always
    ports:
      - "6379:6379"

    networks:
      - app-network


  worker:
    <<: *common-setup

    volumes:
      - ./financial_bot:/application/financial_bot
      - ./migrations:/application/migrations
      - ./alembic.ini:/application/alembic.ini
      - ./core:/application/core
      - ./${LOG_PATH:-./logs}:/application/logs

    command: celery -A core.celery_app:app worker --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      REDIS_URL: ${CELERY_BROKER_URL}
      DATABASE_URL: ${DATABASE_URL_DOCKER}
    env_file:
      - .env


networks:
  app-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1400"


volumes:
  db-data:
