"""adding a user to tweet

Revision ID: 06f8935b6c6b
Revises: 573977ca18f1
Create Date: 2026-01-30 10:45:24.523693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f8935b6c6b'
down_revision: Union[str, Sequence[str], None] = '573977ca18f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tweet', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweet', type_='foreignkey')
    op.drop_column('tweet', 'user_id')
    # ### end Alembic commands ###
