"""Creating Tweet and Media

Revision ID: ae65d2178bec
Revises:
Create Date: 2026-01-23 13:56:04.068377

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae65d2178bec"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tweet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tweet_data", sa.String(length=280), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tweet_id"), "tweet", ["id"], unique=False)
    op.create_table(
        "media",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("tweet_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tweet_id"],
            ["tweet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_media_id"), "media", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_id"), table_name="media")
    op.drop_table("media")
    op.drop_index(op.f("ix_tweet_id"), table_name="tweet")
    op.drop_table("tweet")
    # ### end Alembic commands ###
