"""rename field user in table users

Revision ID: cfee109af0a2
Revises: cd8312ab08f3
Create Date: 2026-02-01 11:04:18.721639

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cfee109af0a2"
down_revision: Union[str, Sequence[str], None] = "cd8312ab08f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "user", new_column_name="name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "name", new_column_name="user")
    # ### end Alembic commands ###
