# mypy: ignore-errors
#flake8: noqa
# type: ignore
"""add timezone field to users and adjustment of other fields

Revision ID: 0108b1c62828
Revises: f275168c575d
Create Date: 2026-09-25 11:22:40.835323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0108b1c62828'
down_revision: Union[str, Sequence[str], None] = 'f275168c575d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_bot', sa.Column('timezone', sa.String(), server_default='UTC', nullable=False))
    op.alter_column('users_bot', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users_bot', 'language_code',
               existing_type=sa.VARCHAR(length=10),
               server_default='en',
               existing_nullable=False)
    op.alter_column('users_bot', 'subscription_type',
               existing_type=sa.VARCHAR(),
               server_default='free',
               existing_nullable=False)
    op.alter_column('users_bot', 'currency',
               existing_type=sa.VARCHAR(),
               server_default='USD',
               existing_nullable=False)
    op.alter_column('users_bot', 'username',
                    type_=sa.String(64),
                    existing_type=sa.String())
    op.alter_column('users_bot', 'first_name',
                    type_=sa.String(64),
                    existing_type=sa.String())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_bot', 'currency',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users_bot', 'subscription_type',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users_bot', 'language_code',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users_bot', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('users_bot', 'timezone')
    op.alter_column('users_bot', 'first_name',
                    type_=sa.String(),
                    existing_type=sa.String(64))
    op.alter_column('users_bot', 'username',
                    type_=sa.String(),
                    existing_type=sa.String(64))
    # ### end Alembic commands ###
