# mypy: ignore-errors
# flake8: noqa
# type: ignore
"""add field batch_id

Revision ID: 4c9bee231689
Revises: e6b288dbe95a
Create Date: 2026-06-29 12:05:44.576745

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c9bee231689"
down_revision: Union[str, Sequence[str], None] = "e6b288dbe95a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("batch_id", sa.String(length=36), nullable=True)
    )
    op.create_index(
        op.f("ix_transactions_batch_id"), "transactions", ["batch_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_batch_id"), table_name="transactions")
    op.drop_column("transactions", "batch_id")
    # ### end Alembic commands ###
