# mypy: ignore-errors
#flake8: noqa
# type: ignore
"""transactions_created_at

Revision ID: 6d44e3117bd6
Revises: c174c71441de
Create Date: 2026-04-28 12:30:38.620913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d44e3117bd6'
down_revision: Union[str, Sequence[str], None] = 'c174c71441de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_column('transactions', 'created_at')
    # ### end Alembic commands ###
