# mypy: ignore-errors
#flake8: noqa
# type: ignore
"""deleted field recipt_photo

Revision ID: a670939d37b9
Revises: a6c5fab342fd
Create Date: 2026-09-25 12:32:29.598396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a670939d37b9'
down_revision: Union[str, Sequence[str], None] = 'a6c5fab342fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'receipt_photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('receipt_photo_url', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
