# mypy: ignore-errors
#flake8: noqa
# type: ignore
"""deleted field ocr

Revision ID: a6c5fab342fd
Revises: 0108b1c62828
Create Date: 2026-09-25 11:59:09.490601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c5fab342fd'
down_revision: Union[str, Sequence[str], None] = '0108b1c62828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_bot', 'first_name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('users_bot', 'ocr_requests_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_bot', sa.Column('ocr_requests_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.alter_column('users_bot', 'first_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
