# mypy: ignore-errors
#flake8: noqa
# type: ignore
"""added UserBot and Transaction

Revision ID: c174c71441de
Revises: c35865c04465
Create Date: 2026-03-26 10:27:59.742492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c174c71441de'
down_revision: Union[str, Sequence[str], None] = 'c35865c04465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_bot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('subscription_type', sa.String(), nullable=False),
    sa.Column('sub_expires_at', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('monthly_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_remind_percent', sa.SmallInteger(), server_default='80', nullable=False),
    sa.Column('savings_goal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_payment_id', sa.String(), nullable=True),
    sa.Column('ocr_requests_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ai_requests_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_request_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_bot_tg_id'), 'users_bot', ['tg_id'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('receipt_photo_url', sa.Text(), nullable=True),
    sa.Column('text_check', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users_bot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_users_bot_tg_id'), table_name='users_bot')
    op.drop_table('users_bot')
    # ### end Alembic commands ###
