# mypy: ignore-errors
"""rename field username in table users

Revision ID: cd8312ab08f3
Revises: 06f8935b6c6b
Create Date: 2026-02-01 09:44:04.919150

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd8312ab08f3"
down_revision: Union[str, Sequence[str], None] = "06f8935b6c6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "username", new_column_name="user")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "user", new_column_name="username")
    # ### end Alembic commands ###
